on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Format code
      run: go fmt ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.1
        install-mode: goinstall

    - name: Test
      run: go test -v ./...
